# プロンプトのバージョンや設定を記述
version = "v0.4.0"
engine = "jinja2" # 変数を埋め込むためのテンプレートエンジンを指定
language = "ja"

[engine_options]
undefined = "debug"

[[messages]]
role = "user"
content = '''
以下の【入力データ】と【作成指示】を読んで、テストデータセットの作成に協力してください。

【入力データ】

質問: {{single_question}}

使用する述語動詞:{{ verb }}

喚起するフレームの情報:{{ definitions_a }}

既存の文:{{ sentence }}

【作成指示】

1. {{sentence}}と同じく、{{verb}}を使ったフレーム{{frame_a}}を喚起する文を作成してください。

ただし、「{{single_question}}」という問題に対し、{{Answer}}が正解となる文にしてください。
※基本的には、正しいフレームを喚起するようにすれば、整合性を保てるはずです。

例文を作る際、以下のルールを守ってください。

ルール(a): 答えのヒントを文中に含めないこと。
例文を作成する際、質問の「答え」そのものを示すような、あからさまな単語を意図的に避けてください。
（悪い例： もし質問が「物理的な移動」の有無を問うものなら、例文中に「彼は移動するために家を出た」のような、答えを直接示す言葉を入れてはいけません。）
ルール(b): 2つの文は、同じフレームを喚起するものの、内容語は似ておらず、文構造が異なるような、意味的な比較が可能なものにしてください。
大まかなトピックや題材は似ているほうが望ましいです。
ルール(c): フレームを喚起する動詞は完了形で、文末に置かなければなりません。
（最重要）ルール(d): 例文は、自然な日本語にしてください。特にその他のルールを守ることで変な日本語になっていないか注意してください。

2. 質問で問われている内容を{{answer_ja}}する文になっているか改めて確認してください。
満たさない場合は文を考え直してください。

出力は以下のjson形式にし、他には何も出力しないでください。jsonのkeyとvalueは」などで終わらせず、"で囲んでください。
{
"generated_sentence": "生成した文",
}
'''